import header from '../objects/header.obj'

describe('Header', () => {
    it('check all header elements are visible for logged out user', () => {
        cy.visit('')
        cy.get(header.logoImage).should('be.visible')
            .and('have.attr', 'src').should('contain', 'logo.png')
        cy.get(header.logoLink).should('have.attr', 'href', '/')
        cy.get(header.navigationLinks).should('be.visible')
                        .and('have.length', 8)
        cy.get(header.homeButton).should('be.visible')
            .and('have.text', ' Home')
            .and('have.attr', 'href', '/')
        cy.get(header.productsButton).should('be.visible')
            .and('have.text', ' Products')
            .and('have.attr', 'href', '/products')
        cy.get(header.cartButton).should('be.visible')
            .and('have.text', ' Cart')
            .and('have.attr', 'href', '/view_cart')
        cy.get(header.authButton).should('be.visible')
            .and('have.text', ' Signup / Login')
            .and('have.attr', 'href', '/login')
        cy.get(header.testCasesButton).should('be.visible')
            .and('have.text', ' Test Cases')
            .and('have.attr', 'href', '/test_cases')
        cy.get(header.apiTestingButton).should('be.visible')
            .and('have.text', ' API Testing')
            .and('have.attr', 'href', '/api_list')
        cy.get(header.videoTutorialsButton).should('be.visible')
            .and('have.text', ' Video Tutorials')
            .and('have.attr', 'href', 'https://www.youtube.com/c/AutomationExercise')
        cy.get(header.contactButton).should('be.visible')
            .and('have.text', ' Contact us')
            .and('have.attr', 'href', '/contact_us')
    })

    it('check all header elements are visible for logged out user', () => {
            cy.loginFrontEnd()
            cy.get(header.logoImage).should('be.visible')
                .and('have.attr', 'src').should('contain', 'logo.png')
            cy.get(header.logoLink).should('have.attr', 'href', '/')
            cy.get(header.navigationLinks).should('be.visible')
                .and('have.length', 10)
            cy.get(header.homeButton).should('be.visible')
                .and('have.text', ' Home')
                .and('have.attr', 'href', '/')
            cy.get(header.productsButton).should('be.visible')
                .and('have.text', ' Products')
                .and('have.attr', 'href', '/products')
            cy.get(header.cartButton).should('be.visible')
                .and('have.text', ' Cart')
                .and('have.attr', 'href', '/view_cart')
            cy.get(header.authButton).should('be.visible')
                .and('have.text', ' Logout')
                .and('have.attr', 'href', '/logout')
            cy.get(header.navigationLinks).eq(4).should('be.visible')
                            .and('have.text', ' Delete Account')
                            .and('have.attr', 'href', '/delete_account')
            cy.get(header.navigationLinks).eq(5).should('be.visible')
                .and('have.text', ' Test Cases')
                .and('have.attr', 'href', '/test_cases')
            cy.get(header.navigationLinks).eq(6).should('be.visible')
                .and('have.text', ' API Testing')
                .and('have.attr', 'href', '/api_list')
            cy.get(header.navigationLinks).eq(7).should('be.visible')
                .and('have.text', ' Video Tutorials')
                .and('have.attr', 'href', 'https://www.youtube.com/c/AutomationExercise')
            cy.get(header.navigationLinks).eq(8).should('be.visible')
                .and('have.text', ' Contact us')
                .and('have.attr', 'href', '/contact_us')
            cy.get(header.userNotification).should('be.visible')
                .and('have.text', ' Logged in as YUQGAUJZUser')
        })

})
