import productPage from '../objects/product_catalog.obj'
import 'cypress-real-events/support'

describe('Product page', () => {
    context('logged out user', () => {
        it('check sidebar categories and brands are displayed correctly', () => {
            cy.visit('/products')
            cy.get(productPage.saleImage).should('be.visible')
                .and('have.attr', 'src').should('contain', 'sale.jpg')
            cy.get(productPage.searchInput).should('be.visible')
            cy.get(productPage.searchButton).should('be.visible')
                .and('be.enabled')
            cy.get(productPage.categoriesHeading).should('be.visible')
                .and('have.text', 'Category')
            cy.get(productPage.allCategories).should('be.visible')
                .and('have.length', 3)
            cy.get(productPage.categoryWomenHeading).should('be.visible')
                .and('contain', 'Women')
            cy.get(productPage.categoryWomenIcon).should('be.visible')
                .and('have.attr', 'class', 'fa fa-plus')
            cy.get(productPage.categoryWomenSubcategories).should('not.be.visible')
            cy.get(productPage.categoryWomenIcon).click()
            cy.get(productPage.categoryWomenSubcategories).should('be.visible')
                .and('have.length', 3)
            cy.get(productPage.categoryWomenSubcategories).eq(0).should('be.visible')
                .and('have.text', 'Dress ')
                .and('have.attr', 'href', '/category_products/1')
            cy.get(productPage.categoryWomenSubcategories).eq(1).should('be.visible')
                .and('have.text', 'Tops ')
                .and('have.attr', 'href', '/category_products/2')
            cy.get(productPage.categoryWomenSubcategories).eq(2).should('be.visible')
                .and('have.text', 'Saree ')
                .and('have.attr', 'href', '/category_products/7')
            cy.get(productPage.categoryMenHeading).should('be.visible')
                .and('contain', 'Men')
            cy.get(productPage.categoryMenIcon).should('be.visible')
                .and('have.attr', 'class', 'fa fa-plus')
            cy.get(productPage.categoryMenSubcategories).should('not.be.visible')
            cy.get(productPage.categoryMenIcon).click()
            cy.get(productPage.categoryWomenSubcategories).should('not.be.visible')
            cy.get(productPage.categoryMenSubcategories).should('be.visible')
                .and('have.length', 2)
            cy.get(productPage.categoryMenSubcategories).eq(0).should('be.visible')
                .and('have.text', 'Tshirts ')
                .and('have.attr', 'href', '/category_products/3')
            cy.get(productPage.categoryMenSubcategories).eq(1).should('be.visible')
                .and('have.text', 'Jeans ')
                .and('have.attr', 'href', '/category_products/6')
            cy.get(productPage.categoryKidsHeading).should('be.visible')
                .and('contain', 'Kids')
            cy.get(productPage.categoryKidsIcon).should('be.visible')
                .and('have.attr', 'class', 'fa fa-plus')
            cy.get(productPage.categoryKidsSubcategories).should('not.be.visible')
            cy.get(productPage.categoryKidsIcon).click()
            cy.get(productPage.categoryKidsSubcategories).should('be.visible')
            cy.get(productPage.categoryMenSubcategories).should('not.be.visible')
                .and('have.length', 2)
            cy.get(productPage.categoryKidsSubcategories).eq(0).should('be.visible')
                .and('have.text', 'Dress ')
                .and('have.attr', 'href', '/category_products/4')
            cy.get(productPage.categoryKidsSubcategories).eq(1).should('be.visible')
                .and('have.text', 'Tops & Shirts ')
                .and('have.attr', 'href', '/category_products/5')
            cy.get(productPage.brandsHeading).should('be.visible')
                .and('have.text', 'Brands')
            cy.get(productPage.brandNames).should('be.visible')
                .and('have.length', 8)
            cy.get(productPage.brandNames).eq(0).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Polo')
                .invoke('text')
                .should('match', /\s\(\d\)Polo/)
            cy.get(productPage.brandNames).eq(1).should('be.visible')
                .and('have.attr', 'href', '/brand_products/H&M')
                .invoke('text')
                .should('match', /\s\(\d\)H&M/)
            cy.get(productPage.brandNames).eq(2).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Madame')
                .invoke('text')
                .should('match', /\s\(\d\)Madame/)
            cy.get(productPage.brandNames).eq(3).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Mast & Harbour')
                .invoke('text')
                .should('match', /\s\(\d\)Mast & Harbour/)
            cy.get(productPage.brandNames).eq(4).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Babyhug')
                .invoke('text')
                .should('match', /\s\(\d\)Babyhug/)
            cy.get(productPage.brandNames).eq(5).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Allen Solly Junior')
                .invoke('text')
                .should('match', /\s\(\d\)Allen Solly Junior/)
            cy.get(productPage.brandNames).eq(6).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Kookie Kids')
                .invoke('text')
                .should('match', /\s\(\d\)Kookie Kids/)
            cy.get(productPage.brandNames).eq(7).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Biba')
                .invoke('text')
                .should('match', /\s\(\d\)Biba/)
        })

        it('check featured product tiles are displayed correctly', () => {
            cy.visit('/products')
            cy.get(productPage.productsHeading).should('be.visible')
                .and('have.text', 'All Products')
            cy.get(productPage.productTile).should('be.visible')
                .and('have.length', 34)
            cy.get(productPage.productTile).first().scrollIntoView()
            cy.get(productPage.productTile).first().should('be.visible').within(() => {
                cy.get(productPage.productImage).should('be.visible')
                    .and('have.attr', 'src').should('contain', 'picture')
                cy.get(productPage.productPrice).should('be.visible')
                    .invoke('text').should('match', /Rs. [0-9]{1,3}/)
                cy.get(productPage.productName).should('be.visible')
                    .invoke('text').should('match', /[A-Za-z]+/)
                cy.get(productPage.addToCartButton).should('be.visible')
                    .and('have.text', 'Add to cart')
                cy.get(productPage.viewProductLink).should('be.visible')
                    .and('have.text', 'View Product')
                    .and('have.attr', 'href')
                    .should('contain', '/product_details/')
            })
            cy.get(productPage.productTile).first().realHover()
            cy.get(productPage.productTile).first().within(() => {
                cy.get(productPage.productOverlay).should('be.visible')
                cy.get(productPage.overlayPrice).should('be.visible')
                    .invoke('text').should('match', /Rs. [0-9]{1,3}/)
                cy.get(productPage.overlayName).should('be.visible')
                    .invoke('text').should('match', /[A-Za-z]+/)
                cy.get(productPage.overlayCartButton).should('be.visible')
                    .and('have.text', 'Add to cart')
            })
        })
    })

    context('logged in user', () => {
        it('check sidebar categories and brands are displayed correctly', () => {
            cy.loginFrontEnd()
            cy.visit('/products')
            cy.get(productPage.saleImage).should('be.visible')
                .and('have.attr', 'src').should('contain', 'sale.jpg')
            cy.get(productPage.searchInput).should('be.visible')
            cy.get(productPage.searchButton).should('be.visible')
                .and('be.enabled')
            cy.get(productPage.categoriesHeading).should('be.visible')
                .and('have.text', 'Category')
            cy.get(productPage.allCategories).should('be.visible')
                .and('have.length', 3)
            cy.get(productPage.categoryWomenHeading).should('be.visible')
                .and('contain', 'Women')
            cy.get(productPage.categoryWomenIcon).should('be.visible')
                .and('have.attr', 'class', 'fa fa-plus')
            cy.get(productPage.categoryWomenSubcategories).should('not.be.visible')
            cy.get(productPage.categoryWomenIcon).click()
            cy.get(productPage.categoryWomenSubcategories).should('be.visible')
                .and('have.length', 3)
            cy.get(productPage.categoryWomenSubcategories).eq(0).should('be.visible')
                .and('have.text', 'Dress ')
                .and('have.attr', 'href', '/category_products/1')
            cy.get(productPage.categoryWomenSubcategories).eq(1).should('be.visible')
                .and('have.text', 'Tops ')
                .and('have.attr', 'href', '/category_products/2')
            cy.get(productPage.categoryWomenSubcategories).eq(2).should('be.visible')
                .and('have.text', 'Saree ')
                .and('have.attr', 'href', '/category_products/7')
            cy.get(productPage.categoryMenHeading).should('be.visible')
                .and('contain', 'Men')
            cy.get(productPage.categoryMenIcon).should('be.visible')
                .and('have.attr', 'class', 'fa fa-plus')
            cy.get(productPage.categoryMenSubcategories).should('not.be.visible')
            cy.get(productPage.categoryMenIcon).click()
            cy.get(productPage.categoryWomenSubcategories).should('not.be.visible')
            cy.get(productPage.categoryMenSubcategories).should('be.visible')
                .and('have.length', 2)
            cy.get(productPage.categoryMenSubcategories).eq(0).should('be.visible')
                .and('have.text', 'Tshirts ')
                .and('have.attr', 'href', '/category_products/3')
            cy.get(productPage.categoryMenSubcategories).eq(1).should('be.visible')
                .and('have.text', 'Jeans ')
                .and('have.attr', 'href', '/category_products/6')
            cy.get(productPage.categoryKidsHeading).should('be.visible')
                .and('contain', 'Kids')
            cy.get(productPage.categoryKidsIcon).should('be.visible')
                .and('have.attr', 'class', 'fa fa-plus')
            cy.get(productPage.categoryKidsSubcategories).should('not.be.visible')
            cy.get(productPage.categoryKidsIcon).click()
            cy.get(productPage.categoryKidsSubcategories).should('be.visible')
            cy.get(productPage.categoryMenSubcategories).should('not.be.visible')
                .and('have.length', 2)
            cy.get(productPage.categoryKidsSubcategories).eq(0).should('be.visible')
                .and('have.text', 'Dress ')
                .and('have.attr', 'href', '/category_products/4')
            cy.get(productPage.categoryKidsSubcategories).eq(1).should('be.visible')
                .and('have.text', 'Tops & Shirts ')
                .and('have.attr', 'href', '/category_products/5')
            cy.get(productPage.brandsHeading).should('be.visible')
                .and('have.text', 'Brands')
            cy.get(productPage.brandNames).should('be.visible')
                .and('have.length', 8)
            cy.get(productPage.brandNames).eq(0).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Polo')
                .invoke('text')
                .should('match', /\s\(\d\)Polo/)
            cy.get(productPage.brandNames).eq(1).should('be.visible')
                .and('have.attr', 'href', '/brand_products/H&M')
                .invoke('text')
                .should('match', /\s\(\d\)H&M/)
            cy.get(productPage.brandNames).eq(2).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Madame')
                .invoke('text')
                .should('match', /\s\(\d\)Madame/)
            cy.get(productPage.brandNames).eq(3).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Mast & Harbour')
                .invoke('text')
                .should('match', /\s\(\d\)Mast & Harbour/)
            cy.get(productPage.brandNames).eq(4).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Babyhug')
                .invoke('text')
                .should('match', /\s\(\d\)Babyhug/)
            cy.get(productPage.brandNames).eq(5).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Allen Solly Junior')
                .invoke('text')
                .should('match', /\s\(\d\)Allen Solly Junior/)
            cy.get(productPage.brandNames).eq(6).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Kookie Kids')
                .invoke('text')
                .should('match', /\s\(\d\)Kookie Kids/)
            cy.get(productPage.brandNames).eq(7).should('be.visible')
                .and('have.attr', 'href', '/brand_products/Biba')
                .invoke('text')
                .should('match', /\s\(\d\)Biba/)
        })

        it('check featured product tiles are displayed correctly', () => {
            cy.loginFrontEnd()
            cy.visit('/products')
            cy.get(productPage.productsHeading).should('be.visible')
                .and('have.text', 'All Products')
            cy.get(productPage.productTile).should('be.visible')
                .and('have.length', 34)
            cy.get(productPage.productTile).first().scrollIntoView()
            cy.get(productPage.productTile).first().should('be.visible').within(() => {
                cy.get(productPage.productImage).should('be.visible')
                    .and('have.attr', 'src').should('contain', 'picture')
                cy.get(productPage.productPrice).should('be.visible')
                    .invoke('text').should('match', /Rs. [0-9]{1,3}/)
                cy.get(productPage.productName).should('be.visible')
                    .invoke('text').should('match', /[A-Za-z]+/)
                cy.get(productPage.addToCartButton).should('be.visible')
                    .and('have.text', 'Add to cart')
                cy.get(productPage.viewProductLink).should('be.visible')
                    .and('have.text', 'View Product')
                    .and('have.attr', 'href')
                    .should('contain', '/product_details/')
            })
            cy.get(productPage.productTile).first().realHover()
            cy.get(productPage.productTile).first().within(() => {
                cy.get(productPage.productOverlay).should('be.visible')
                cy.get(productPage.overlayPrice).should('be.visible')
                    .invoke('text').should('match', /Rs. [0-9]{1,3}/)
                cy.get(productPage.overlayName).should('be.visible')
                    .invoke('text').should('match', /[A-Za-z]+/)
                cy.get(productPage.overlayCartButton).should('be.visible')
                    .and('have.text', 'Add to cart')
            })
        })
    })
})
