const area = '#form'
const signupArea = `${area} .signup-form`
const signupForm = `.login-form`
module.exports = {
    // signup section on login page
    signupHeader: `${signupArea} :first-child`,
    nameInput:  `${signupArea} [data-qa=signup-name]`,
    emailInput: `${signupArea} [data-qa=signup-email]`,
    signupButton: `${signupArea} [data-qa=signup-button]`,
    errorMessage: `${signupArea} form p`,
    // signup form
    formHeader: `${signupForm} :nth-child(1) > b`,
    titleLabel: `${signupForm} .clearfix > :first-child`,
    mrRadio: `${signupForm} .clearfix #id_gender1`,
    mrsRadio: `${signupForm} .clearfix #id_gender2`,
    mrRadioLabel: `${signupForm} [for=id_gender1]`,
    mrsRadioLabel: `${signupForm} [for=id_gender2]`,
    nameLabel: `${signupForm} .required [for=name]`,
    nameField: `${signupForm} [data-qa=name]`,
    emailLabel: `${signupForm} .required [for=email]`,
    emailField: `${signupForm} [data-qa=email]`,
    passwordLabel: `${signupForm} .required [for=password]`,
    passwordField: `${signupForm} [data-qa=password]`,
    birthDateLabel: `${signupForm} :nth-child(6) label`,
    daySelector: `${signupForm} #uniform-days select`,
    monthSelector: `${signupForm} #uniform-months select`,
    yearSelector: `${signupForm} #uniform-years select`,
    newsletterCheckbox: `${signupForm} #uniform-newsletter input`,
    newsletterCheckboxLabel: `${signupForm} [for=newsletter]`,
    partnersCheckbox: `${signupForm} #uniform-optin input`,
    partnersCheckboxLabel: `${signupForm} [for=optin]`,
    addressHeader: `${signupForm} > form > .title > b`,
    firstNameLabel: `${signupForm} [for=first_name]`,
    firstNameField: `${signupForm} [data-qa=first_name]`,
    lastNameLabel: `${signupForm} [for=last_name]`,
    lastNameField: `${signupForm} [data-qa=last_name]`,
    companyLabel: `${signupForm} [for=company]`,
    companyField: `${signupForm} [data-qa=company]`,
    addressLine1Label: `${signupForm} [for=address1]`,
    addressLine1Info: `${signupForm} [for=address1] .inline-infos`,
    addressLine1Field: `${signupForm} [data-qa=address]`,
    addressLine2Label: `${signupForm} [for=address2]`,
    addressLine2Field: `${signupForm} [data-qa=address2]`,
    countryLabel: `${signupForm} :nth-child(16) > label`,
    countrySelector: `${signupForm} [data-qa=country]`,
    stateLabel: `${signupForm} [for=state]`,
    stateField: `${signupForm} [data-qa=state]`,
    cityLabel: `${signupForm} form > :nth-child(18) label`,
    cityField: `${signupForm} [data-qa=city]`,
    zipcodeLabel: `${signupForm} form > :nth-child(19) label`,
    zipcodeField: `${signupForm} [data-qa=zipcode]`,
    phoneLabel: `${signupForm} [for=mobile_number]`,
    phoneField: `${signupForm} [data-qa=mobile_number]`,
    createAccountButton: `${signupForm} [data-qa=create-account]`,
    scrollUpButton: '#scrollUp',
    // success page
    accountCreatedHeader: `${area} h2`,
    accountCreatedText: `${area} p`,
    continueButton: '[data-qa=continue-button]'
 }